all:
  hosts:
    master1:
      ansible_host: 10.89.243.125
      ip: 10.89.243.125
      access_ip: 10.89.243.125
      ansible_user: rocky
    master2:
      ansible_host: 10.89.243.138
      ip: 10.89.243.138
      access_ip: 10.89.243.138
      ansible_user: rocky
    master3:
      ansible_host: 10.89.243.64
      ip: 10.89.243.64
      access_ip: 10.89.243.64
      ansible_user: rocky
    worker1:
      ansible_host: 10.89.243.194
      ip: 10.89.243.194
      access_ip: 10.89.243.194
      ansible_user: rocky
    worker2:
      ansible_host: 10.89.243.103
      ip: 10.89.243.103
      access_ip: 10.89.243.103
      ansible_user: rocky
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    kube_node:
      hosts:
        worker1:
        worker2:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}